version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - ./app:/srv

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - php

volumes:
  caddy_data:
