version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - ./app:/srv

volumes:
  caddy_data:
  caddy_config:
