install:
	git clone git@github.com:14code/chesskeeper-infra.git /opt/chesskeeper
	cd /opt/chesskeeper && git clone git@github.com:14code/chesskeeper.git app
	cd /opt/chesskeeper && docker compose up -d --build

volume:
	bash scripts/prepare-volume.sh
